name: "Jenny Lee's Site"
favicon: null
layout_spectrum: 0.89227
typography_spectrum: 0.29564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#423155'
    - '#aa6cc1'
    - '#4b9abb'
    - '#54d0f6'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
