name: "Jenny Lee's Site"
favicon: null
layout_spectrum: 0.03747409791685641
typography_spectrum: 0.6625268012285233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2704763161018491
  lightness: 0.6127886280883104
  saturation: 0.4565272689796984
  rhythmicContrast: 0.08808889938518405
purpose: []
